language: perl
perl:
   - '5.20'
matrix:
   fast_finish: true
before_install:
   - export AUTOMATED_TESTING=1 NONINTERACTIVE_TESTING=1 HARNESS_OPTIONS=j10:c HARNESS_TIMER=1
   - git clone git://github.com/haarg/perl-travis-helper
   - source perl-travis-helper/init
   - build-perl
   - perl -V
   - git config --global user.name "TravisCI"
   - git config --global user.email $HOSTNAME":not-for-mail@travis-ci.org"
   - sudo apt-get update -qq
   - sudo apt-get remove --purge debhelper file libtool
   - sudo apt-get install --yes --force-yes aptitude
   - sudo aptitude install -y devscripts
   - dget -x -u http://archive.ubuntu.com/ubuntu/pool/main/c/cmake/cmake_2.8.12.2-0ubuntu3.devscripts
   - sudo aptitude build-dep cmake
   - cd cmake* && fakeroot dpkg-buildpackage -d
   - sudo dpkg -i ../cmake*deb
   - cd ..
install:
   - git clone https://github.com/jgm/CommonMark.git CommonMark
   - cd CommonMark
   - make
   - sudo make install
   - cd ..
   - cpanm --quiet --notest --skip-satisfied Dist::Zilla
   - "dzil authordeps          --missing | grep -vP '[^\\w:]' | xargs -n 5 -P 10 cpanm --quiet --notest"
   - "dzil listdeps   --author --missing | grep -vP '[^\\w:]' | cpanm --verbose"
script:
   - dzil smoke --release --author
